global:
  strip_outer_whitespace: true
  collapse_inter_tag_whitespace: true
  drop_empty_tables: false
  header_body_mismatch_ratio_warn: 0.2
  header_body_cell_count_mismatch_ratio_warn: 0.2
  possible_column_merge_delta: 1

per_type:
  table:
    drop_empty_tables: false
  diagram:
    drop_empty_tables: true
  scan:
    drop_empty_tables: false
